In [2]:
import pandas as pd

## Abrir Tablas

In [4]:
df_central = pd.read_csv("../ttransporte_eod2017/conjunto_de_datos/ttransporte.csv")
df_tviaje = pd.read_csv("../tviaje_eod2017/conjunto_de_datos/tviaje.csv")

## Checar congruencia de registros

In [15]:
df_central.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 890748 entries, 0 to 890747
Data columns (total 18 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id_tra     890748 non-null  int64
 1   id_via     890748 non-null  int64
 2   p5_3       890748 non-null  int64
 3   n_via      890748 non-null  int64
 4   p5_14      890748 non-null  int64
 5   p5_16      890748 non-null  int64
 6   p5_16_1_1  890748 non-null  int64
 7   p5_16_1_2  890748 non-null  int64
 8   p5_16_2    274526 non-null  float64
 9   p5_17_1c   87931 non-null   float64
 10  p5_17_2c   87931 non-null   float64
 11  estrato    890748 non-null  int64
 12  factor     890748 non-null  int64
 13  upm_dis    890748 non-null  int64
 14  est_dis    890748 non-null  int64
 15  tloc       890748 non-null  int64
 16  sexo       890748 non-null  int64
 17  edad       890748 non-null  int64
dtypes: float64(3), int64(15)
memory usage: 122.3 MB

In [16]:
df_tviaje.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531594 entries, 0 to 531593
Data columns (total 82 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id_via      531594 non-null  int64
 1   id_soc      531594 non-null  int64
 2   p5_3        531594 non-null  int64
 3   n_via       531594 non-null  int64
 4   p5_6        531594 non-null  int64
 5   p5_7_6      531594 non-null  int64
 6   p5_7_7      531594 non-null  int64
 7   dto_origen  531594 non-null  int64
 8   p5_9_1      531594 non-null  int64
 9   p5_9_2      531594 non-null  int64
 10  p5_10_1     531594 non-null  int64
 11  p5_10_2     531594 non-null  int64
 12  p5_11a      531594 non-null  int64
 13  p5_12_6     531594 non-null  int64
 14  p5_12_7     531594 non-null  int64
 15  dto_dest    531594 non-null  int64
 16  p5_13       531594 non-null  int64
 17  p5_14_01    531594 non-null  int64
 18  p5_15_01    112248 non-null  float64
 19  p5_14_02    531594 non-null  int64
 20  p5_15_02    175939 non-null  float64
 21  p5_14_03    531594 non-null  int64
 22  p5_15_03    2739 non-null    float64
 23  p5_14_04    531594 non-null  int64
 24  p5_15_04    25835 non-null   float64
 25  p5_14_05    531594 non-null  int64
 26  p5_15_05    67395 non-null   float64
 27  p5_14_06    531594 non-null  int64
 28  p5_15_06    6123 non-null    float64
 29  p5_14_07    531594 non-null  int64
 30  p5_15_07    11943 non-null   float64
 31  p5_14_08    531594 non-null  int64
 32  p5_15_08    14151 non-null   float64
 33  p5_14_09    531594 non-null  int64
 34  p5_15_09    5749 non-null    float64
 35  p5_14_10    531594 non-null  int64
 36  p5_15_10    1998 non-null    float64
 37  p5_14_11    531594 non-null  int64
 38  p5_15_11    16018 non-null   float64
 39  p5_14_12    531594 non-null  int64
 40  p5_15_12    1597 non-null    float64
 41  p5_14_13    531594 non-null  int64
 42  p5_15_13    2552 non-null    float64
 43  p5_14_14    531594 non-null  int64
 44  p5_15_14    322173 non-null  float64
 45  p5_14_15    531594 non-null  int64
 46  p5_15_15    129 non-null     float64
 47  p5_14_16    531594 non-null  int64
 48  p5_15_16    1538 non-null    float64
 49  p5_14_17    531594 non-null  int64
 50  p5_15_17    4397 non-null    float64
 51  p5_14_18    531594 non-null  int64
 52  p5_15_18    2611 non-null    float64
 53  p5_14_19    531594 non-null  int64
 54  p5_15_19    535 non-null     float64
 55  p5_14_20    531594 non-null  int64
 56  p5_15_20    698 non-null     float64
 57  p5_18       105763 non-null  float64
 58  p5_19       69529 non-null   float64
 59  p5_20       69529 non-null   float64
 60  p5_21_1     41495 non-null   float64
 61  p5_21_2     41495 non-null   float64
 62  p5_22       41495 non-null   float64
 63  p5_23       6950 non-null    float64
 64  p5_24       6950 non-null    float64
 65  p5_25       65021 non-null   float64
 66  p5_26       531594 non-null  int64
 67  p5_27_1     38405 non-null   float64
 68  p5_27_2     38405 non-null   float64
 69  p5_27_3     38405 non-null   float64
 70  p5_27_4     38405 non-null   float64
 71  p5_27_5     38405 non-null   float64
 72  p5_27_6     38405 non-null   float64
 73  p5_27_7     38405 non-null   float64
 74  p5_27_8     38405 non-null   float64
 75  estrato     531594 non-null  int64
 76  factor      531594 non-null  int64
 77  upm_dis     531594 non-null  int64
 78  est_dis     531594 non-null  int64
 79  tloc        531594 non-null  int64
 80  sexo        531594 non-null  int64
 81  edad        531594 non-null  int64
dtypes: float64(37), int64(45)
memory usage: 332.6 MB

In [17]:
df_central.head()

,id_tra,id_via,p5_3,n_via,p5_14,p5_16,p5_16_1_1,p5_16_1_2,p5_16_2,p5_17_1c,p5_17_2c,estrato,factor,upm_dis,est_dis,tloc,sexo,edad
0,3198,1810,2,2,14,2,0,5,NaN,NaN,NaN,3,120,59,20,1,2,55
1,3199,1811,1,1,2,3,0,25,6.0,NaN,NaN,3,120,59,20,1,2,38
2,3200,1811,1,1,5,2,0,40,NaN,15.0,48.0,3,120,59,20,1,2,38
3,3201,1811,1,1,14,1,0,5,NaN,NaN,NaN,3,120,59,20,1,2,38
4,3202,1811,1,1,14,4,0,5,NaN,NaN,NaN,3,120,59,20,1,2,38

In [18]:
df_tviaje.head()

,id_via,id_soc,p5_3,n_via,p5_6,p5_7_6,p5_7_7,dto_origen,p5_9_1,p5_9_2,...,p5_27_6,p5_27_7,p5_27_8,estrato,factor,upm_dis,est_dis,tloc,sexo,edad
0,2936,1268,1,1,1,15,9,2,8,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
1,2937,1268,1,2,3,16,9,16,14,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
2,2938,1268,2,1,1,15,9,2,17,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
3,2939,1268,2,2,7,15,9,2,23,0,...,NaN,NaN,NaN,3,244,87,40,1,2,26
4,2940,1269,1,1,1,15,9,2,8,0,...,NaN,NaN,NaN,3,244,87,40,1,2,22

Buscar si hay ids de `id_via` que no están en ambos

In [19]:
ids_central = set(df_central["id_via"])
ids_tviaje  = set(df_tviaje["id_via"])

missing_in_tviaje = ids_central - ids_tviaje

missing_in_central = ids_tviaje - ids_central

print("Missing in df_tviaje:", missing_in_tviaje)
print("Missing in df_central:", missing_in_central)

Missing in df_tviaje: set()
Missing in df_central: set()

In [20]:
df_central["id_via"].nunique()

531594

In [21]:
df_tviaje["id_via"].nunique()

531594

Todos los ids están presentes; por lo que se juntarán ambas tablas mediante un left join

In [23]:
df_merged = df_central.merge(
    df_tviaje[["id_via", "p5_6", "p5_13"]],
    on="id_via",
    how="left"
)
df_merged

,id_tra,id_via,p5_3,n_via,p5_14,p5_16,p5_16_1_1,p5_16_1_2,p5_16_2,p5_17_1c,p5_17_2c,estrato,factor,upm_dis,est_dis,tloc,sexo,edad,p5_6,p5_13
0,3198,1810,2,2,14,2,0,5,NaN,NaN,NaN,3,120,59,20,1,2,55,11,1
1,3199,1811,1,1,2,3,0,25,6.0,NaN,NaN,3,120,59,20,1,2,38,1,2
2,3200,1811,1,1,5,2,0,40,NaN,15.0,48.0,3,120,59,20,1,2,38,1,2
3,3201,1811,1,1,14,1,0,5,NaN,NaN,NaN,3,120,59,20,1,2,38,1,2
4,3202,1811,1,1,14,4,0,5,NaN,NaN,NaN,3,120,59,20,1,2,38,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890743,886287,528949,2,1,1,1,1,0,NaN,NaN,NaN,2,62,12296,5460,2,1,47,6,2
890744,886288,528950,2,2,14,1,0,30,NaN,NaN,NaN,2,62,12296,5460,2,1,47,3,1
890745,886289,528951,1,1,2,2,0,30,8.0,NaN,NaN,2,62,12296,5460,2,2,49,1,2
890746,886290,528951,1,1,14,1,0,10,NaN,NaN,NaN,2,62,12296,5460,2,2,49,1,2
890747,886291,528952,1,2,2,1,99,99,8.0,NaN,NaN,2,62,12296,5460,2,2,49,5,1

Ahora checamos nans en df_merged en las columnas agregadas

In [24]:
df_merged[["p5_13", "p5_6"]].isna().sum()

p5_13    0
p5_6     0
dtype: int64

Se hizo correctamente el merge.

# Revisar datos

Ver si la columna `p5_16_1_2` es solo una conversión de `p5_16_1_1`

In [ ]:
filtered_df = df_central[df_central["p5_16_1_2"] >= 60]
filtered_df

,id_tra,id_via,p5_3,n_via,p5_14,p5_16,p5_16_1_1,p5_16_1_2,p5_16_2,p5_17_1c,p5_17_2c,estrato,factor,upm_dis,est_dis,tloc,sexo,edad
949,4147,2312,2,1,5,2,99,99,NaN,83.0,14.0,3,109,71,40,1,1,67
950,4148,2312,2,1,11,3,99,99,NaN,296.0,280.0,3,109,71,40,1,1,67
951,4149,2312,2,1,14,1,99,99,NaN,NaN,NaN,3,109,71,40,1,1,67
1772,4970,2748,1,1,1,1,99,99,NaN,NaN,NaN,3,168,82,40,1,2,51
1863,5061,2798,2,2,8,1,99,99,6.0,NaN,NaN,3,168,82,40,1,1,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890434,885978,528723,1,1,14,1,99,99,NaN,NaN,NaN,2,72,12292,5460,2,2,42
890435,885979,528723,1,1,14,3,99,99,NaN,NaN,NaN,2,72,12292,5460,2,2,42
890688,886232,528898,1,1,8,2,99,99,36.0,NaN,NaN,2,170,12295,5460,2,1,24
890689,886233,528898,1,1,14,1,99,99,NaN,NaN,NaN,2,170,12295,5460,2,1,24
890747,886291,528952,1,2,2,1,99,99,8.0,NaN,NaN,2,62,12296,5460,2,2,49

Nos damos cuenta que no, cuando `p5_16_1_2` llega a 60, se cambia a `p5_16_1_1`. También notamos que hay registros con 99 en ambas columnas, que puede indicar un error de captura.

Ahora exportamos el df.

In [ ]:
#df_merged.to_csv("datos_limpios_INEGI.csv", index=False)

In [4]:
df = pd.read_csv("../Limpieza_Datos/datos_limpios_INEGI.csv")
df.head()

,id_tra,id_via,p5_3,n_via,p5_14,p5_16,p5_16_1_1,p5_16_1_2,p5_16_2,p5_17_1c,p5_17_2c,estrato,factor,upm_dis,est_dis,tloc,sexo,edad,p5_6,p5_13
0,3198,1810,2,2,14,2,0,5,NaN,NaN,NaN,3,120,59,20,1,2,55,11,1
1,3199,1811,1,1,2,3,0,25,6.0,NaN,NaN,3,120,59,20,1,2,38,1,2
2,3200,1811,1,1,5,2,0,40,NaN,15.0,48.0,3,120,59,20,1,2,38,1,2
3,3201,1811,1,1,14,1,0,5,NaN,NaN,NaN,3,120,59,20,1,2,38,1,2
4,3202,1811,1,1,14,4,0,5,NaN,NaN,NaN,3,120,59,20,1,2,38,1,2